### ISSUE TITLE
"Incorrect Padding" error

### ISSUE THREAD

**Issue by CodeSoftGitHub** [TimMcCool/scratchattach#141] opened 2023-09-21 01:11 UTC
### The error:
Caught error in request 'verify_code' - Full error below
Incorrect padding

### The code causing the error:
```
@client.request
def verify_code(code):
  return totp.verify(code)
```

### My full code:
```
# --- INSTALLATION --- #
import os
##os.system("pip install scratchattach")

import scratchattach as scratch3
from flask import Flask
import pyotp
import qrcode

key = "SCRATCHATTATCHOTP"
totp = pyotp.TOTP(key)

def get_uri(username):
  return pyotp.totp.TOTP(key).provisioning_uri(name=username, issuer_name="Python OTP Test")

session = scratch3.Session(os.environ["SESSION"], username="CodeSoft_Games") #Replace with your username
conn = session.connect_cloud(project_id="896374139") #Replace with your project id
client = scratch3.CloudRequests(conn)


# --- EXAMPLE REQUESTS ---#
# You can remove these requests and add your own.

@client.request
def ping():
    return "pong"

@client.request
def generate_code(username):
    qrcode.make(get_uri(username)).save("totp.png")
    return get_uri(username)

@client.request
def verify_code(code):
  return totp.verify(code)

# --- SERVER --- #

app = Flask(__name__)

@app.route('/')
def index():
    return 'Server is up'

#These lines start the client and a server.
#You can keep the repl running by pinging its address.
client.run()
##app.run("0.0.0.0", port=8080)
```

**Comment by programORdie2** [comment] 2023-09-21 17:43
I think you only wrote 2 spaces, not 3

**Comment by CodeSoftGitHub** [comment] 2023-09-21 22:11
> I think you only wrote 2 spaces, not 3

Thought it worked but it didn't

**Comment by programORdie2** [comment] 2023-09-22 15:07
Full error plz?

**Comment by CodeSoftGitHub** [comment] 2023-09-22 22:46
> @programORdie2 
> Full error plz?

It just says "Incorrect padding" in console

**Comment by programORdie2** [comment] 2023-09-23 07:22
Nothing else?

**Comment by TimMcCool** [comment] 2023-09-23 13:43
Disable automatic exception handling:
```
client = scratch3.CloudRequests(conn, ignore_exceptions=False)
```

Then it will give you the full error in the console. This will help you to fix the problem

**Comment by CodeSoftGitHub** [comment] 2023-09-24 00:03
```
Exception in request 'verify_code':
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    client.run()
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/scratchattach/_cloud_requests.py", line 99, in run
    self._run(events, data_from_websocket=data_from_websocket)
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/scratchattach/_cloud_requests.py", line 189, in _run
    raise(e)
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/scratchattach/_cloud_requests.py", line 177, in _run
    output = commands[0](*arguments)
  File "main.py", line 35, in verify_code
    return totp.verify(code)
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/pyotp/totp.py", line 84, in verify
    return utils.strings_equal(str(otp), str(self.at(for_time)))
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/pyotp/totp.py", line 56, in at
    return self.generate_otp(self.timecode(for_time) + counter_offset)
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/pyotp/otp.py", line 35, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
  File "/home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/pyotp/otp.py", line 52, in byte_secret
    return base64.b32decode(secret, casefold=True)
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/base64.py", line 235, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding
```

**Comment by programORdie2** [comment] 2023-09-24 06:34
Looks like a problem with the library

**Comment by TimMcCool** [comment] 2023-09-24 14:59
To me it doesn't look like a problem with the library. The error is caused by line 35 of your code / the `totp.verify(code)` function

**Comment by TimMcCool** [comment] 2023-09-25 15:43
The error goes to the "main.py" file (OP's code), then it goes to "home/runner/Scratchattach-Cloud-Requests-Template/venv/lib/python3.8/site-packages/pyotp/totp.py" (not part of scratchattach's backend code). 

"/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/base64.py" isn't part of scratchattch's backend code either, nor is it used by scratchattach. Do you know how tracebacks work?

**Comment by TimMcCool** [comment] 2023-09-26 18:07
I'm closing this because the error is not caused by the library and the OP didn't provide enough information for the community to fix the issue.

**Closed by TimMcCool** 2023-09-26 18:07 UTC
Labels: issue
