### ISSUE TITLE
Scratchattach hanging on conn.get_var("hi").

### ISSUE THREAD

**Issue by BenPI88** [TimMcCool/scratchattach#38] opened 2022-10-02 23:36 UTC
Any Fixes?

**Comment by jimjamgithub** [comment] 2022-10-10 07:09
and the variable name is correct?

**Comment by BenPI88** [comment] 2022-10-15 18:20
> and the variable name correct?

Yes.

**Comment by TimMcCool** [comment] 2022-10-20 20:17
Interesting. Maybe try using scratch3.get_var("project_id", "variable_name") instead. This function does the same, but it tries to get the value from the clouddata logos

**Comment by TimMcCool** [comment] 2022-10-20 20:24
This doesn't look like a bug. Try using scratch3.get_var("project_id", "variable_name") if conn.get_var isn't working for you

**Comment by TimMcCool** [comment] 2022-11-05 00:22
Turned out this may actually be a bug that occurs then getting a turbowarp cloud variable. I'll look into it.

**Comment by TimMcCool** [comment] 2022-11-07 18:46
The issue is caused by turbowarp's updated cloud variable guidelines. Will be fixed soon.

**Comment by TimMcCool** [comment] 2022-11-07 19:05
Scratchattach is only hanging on conn.get_var if the variable doesn't exist. This issue will be fixed.

**Closed by TimMcCool** 2022-11-07 19:05 UTC
Labels: bug
