### ISSUE TITLE
Cloud Requests bug when requsting a { with out the other }

### ISSUE THREAD

**Issue by 3030years** [TimMcCool/scratchattach#51] opened 2022-11-23 22:10 UTC
I was testing this to see if this will work in my scratch os but when i try to add a { it bugs
```
PS C:\Users\Nathan> & C:/Python/python.exe c:/Users/User/Desktop/Stuff/cloudbreaker.py
If you use CloudRequests in your Scratch project, please credit TimMcCool!
Request handler is running
Caught error in request 'BugFinder' - Full error below
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\scratchattach\_cloud_requests.py", line 61, in call_request
    output = req_obj["on_call"](*arguments)
TypeError: BugFinder() takes 1 positional argument but 2 were given

**Comment by TimMcCool** [comment] 2022-12-14 11:58
can I see your code?

**Comment by Ellirio2** [comment] 2022-12-16 19:42
prob cus you gave 1 argument e.g send request (name) argument 1 (a1)  argument 2but in the code youll be saying like name(a1)
so add  the one you need or in Scratch Code remove a request

**Comment by TheCommCraft** [comment] 2023-06-08 14:01
It is because scratchattach doesn't have a default character for encoding characters it doesn't know. When you are prompting the chatbot, you are trying to send "BugFinder&{" and the way scratchattach encodes strings makes it so that if scratchattach doesn't know a character, the character before gets encoded instead. So the server receives "BugFinder&&" which gets interpreted as two arguments intead of one which causes the error.

**Comment by TimMcCool** [comment] 2023-06-10 13:54
This issue is caused by scratchattach's encoder (@TheCommCraft already explained it). The easiest way to fix it: Go to the Cloud Requests sprite in the Scratch project and replace the define _Encode (input) block with this:
![image](https://github.com/TimMcCool/scratchattach/assets/53166177/af92d008-9e6f-42a7-8ed8-12e457a47d7f)

This will make the encoder ignore unsupported characters

**Comment by TimMcCool** [comment] 2023-06-17 18:13
I'm closing this because

**Closed by TimMcCool** 2023-06-17 18:13 UTC
Labels: issue
