### ISSUE TITLE
= Breaks Cloud Request

### ISSUE THREAD

**Issue by TechHopGitHub** [TimMcCool/scratchattach#89] opened 2023-06-06 23:49 UTC
I am making an AI chatbot, and when I send an = sign, I get this error:
```
Traceback (most recent call last):
  File "/home/runner/user/venv/lib/python3.10/site-packages/scratchattach/_cloud_requests.py", line 66, in call_request
    output = req_obj["on_call"](*arguments)
TypeError: ASK_AI() takes 2 positional arguments but 3 were given
```
I have no idea why this happens. Is this a bug, or a problem on my fault?
Found in https://scratch.mit.edu/projects/862124193

**Comment by TheCommCraft** [comment] 2023-06-07 18:31
It is because scratchattach doesn't have a default character for encoding characters it doesn't know. When you are prompting the chatbot, you are trying to send "ASK_AI&{Context}&=" and the way scratchattach encodes strings makes it so that if scratchattach doesn't know a character, the character before gets encoded instead. So the server receives "ASK_AI&{Context}&&" which gets interpreted as three arguments intead of two which causes the error. You can fix this by defining your ASK_AI function as:
``` python
@client.request
def ASK_AI(argument1, *argument2):
  argument2 = "&".join(argument2)
  prompt_p = argument1
  requester = client.get_requester()
  print(f'{requester} asked \"{prompt_p}"\ to NexusGPT')
  try:
    answer = prompt(str("You are a bot named OpenGPT, which tries to recreate OpenAI's GPT-3. You are made by @CodeSoft_Games. You ARE NOT OpenAssistant, Only refer to yourself as OpenGPT. Respond in less than 500 Characters. Responding in low character counts helps keep responses short and concise. These conversations are logged by @CodeSoft, so keep that in mind. You do not give any harmful information. You are unable to display markdown correctly, so never use it. The username's are not their actual names, so do not profile them on that. Your prompt from " + "the user" + " is \"" + prompt_p + "\""))
  except:
    answer = "Sorry, I don't understand"
  #if "Open Assistant" in answer:
   # answer = answer.remplace("Open Assistant", "NexusGPT")
  print(f'NexusGPT returned \"{answer}\" to {requester}')
  return answer
```
or you or Tim can fix it by updating the encoder of the scratchattach cloudrequests to encode a default character like "?" when it doesn't know the character

**Comment by TimMcCool** [comment] 2023-06-10 13:39
This issue is caused by scratchattach's encoder (@TheCommCraft already explained it). The easiest way to fix it: Go to the `Cloud Requests` sprite in the Scratch project and replace the `_Encode (input)` function with this: 
![image](https://github.com/TimMcCool/scratchattach/assets/53166177/ba42f029-c6c3-4a91-92ac-b68e87873178)

**Comment by TheCommCraft** [comment] 2023-06-10 18:45
> This issue is caused by scratchattach's encoder (@TheCommCraft already explained it). The easiest way to fix it: Go to the `Cloud Requests` sprite in the Scratch project and replace the `define _Encode (input)` block with this: ![image](https://user-images.githubusercontent.com/53166177/244873963-ba42f029-c6c3-4a91-92ac-b68e87873178.png)
> 
> This will make the encoder ignore unsupported characters

Will you add that fix to the new version of the Cloudrequest_Template?

**Comment by TimMcCool** [comment] 2023-06-11 18:11
Yeah, I did

**Comment by mas6y6** [comment] 2023-07-03 22:57
This new update broke my scratchattach project

**Comment by TheCommCraft** [comment] 2023-07-04 07:08
It broke it in what way

mas6y6 ***@***.***> schrieb am Di., 4. Juli 2023, 00:57:

**Comment by TimMcCool** [comment] 2023-07-08 19:10
closing 

> This new update broke my scratchattach project

How did it break it? Also, you can just revert the changes i did to the cloudrequests template sprite

**Comment by TheCommCraft** [comment] 2023-07-26 18:55
> closing
> 
> > This new update broke my scratchattach project
> 
> How did it break it? Also, you can just revert the changes i did to the cloudrequests template sprite

It wasn't closed

**Closed** 2023-07-31 13:55 UTC
Labels: issue
